name: spandak8s
base: core22
version: '0.1.0'
summary: A CLI for the Spanda AI Platform
description: |
  The official command-line tool to manage tenants, modules,
  and applications on the Spanda AI Platform. Provides imperative
  control over platform components like MinIO, Spark, Dremio,
  and other data lake infrastructure.

grade: devel # Change to 'stable' for production releases
confinement: strict # Use strict confinement for security

parts:
  # Part 1: Your CLI's source code
  spanda-cli-code:
    plugin: python
    source: .
    python-packages:
      - requests
      - pyyaml
      - click
      - kubernetes
      - rich  # For beautiful CLI output
    stage-packages:
      - git  # For git operations if needed

  # Part 2: The kubectl binary dependency
  kubectl:
    plugin: dump
    source: https://dl.k8s.io/release/v1.28.3/bin/linux/amd64/kubectl
    source-type: file
    organize:
      kubectl: bin/kubectl
    stage:
      - bin/kubectl

  # Part 3: The helm binary dependency  
  helm:
    plugin: dump
    source: https://get.helm.sh/helm-v3.13.2-linux-amd64.tar.gz
    source-type: tar
    organize:
      linux-amd64/helm: bin/helm
    stage:
      - bin/helm

  # REMOVED: platform-charts part completely removed
  # Module templates are now served by the backend API for security and IP protection

apps:
  # Main CLI command
  spandak8s:
    command: bin/spandak8s
    plugs:
      - home          # Access to ~/.spanda/config and ~/.kube/config
      - network       # API calls to backend and Kubernetes clusters
      - network-bind  # If running local backend server

  # Alias for shorter command
  sk8s:
    command: bin/spandak8s
    plugs:
      - home
      - network
      - network-bind

# Define the permissions your CLI needs
plugs:
  home:
    read: all
  network:
  network-bind:

# REMOVED: layout section no longer needed as no local charts are included
